# -*- coding: utf-8 -*-
"""Copy of Practise questions.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/16B9qUvYGsa23PYt0ynILz291ReEWJVVw
"""





"""Practise Question 1 : Read and Print the name and phone number of the user

"""

name = input(" Enter your name")
phonenumber=input()

print(name)
print(phonenumber)

"""Practise Question 1 :  Given 2 numbers, return product if it is less than  or equal to 1000 else return the sum"""

print("PRODUCT / SUM PROBLEM")
num1 = int(input("enter the first number "))
num2 = int(input("enter the second number"))
result = num1 * num2
if(result>=1000):
  result = num1+num2
print("the result is ", result)

"""Practise Question 2 :  Print first 10 natural nos"""

for i in range (1,11):
  print(i)

"""Practise Question 3 : Print first 10 natural nos and its accumulated sum"""

sum=0
for i in range(1,11):
  num = i
  sum = sum+ num
  print(num,"   ",sum)

"""Practise Question 5 :  Printing the characters of the string being entered one below the other"""

string1 = input("enter the string")
for i in string1:
  print(i)

"""Practise Question 6: Print the characters at even location"""

string1 = input("enter the string")
length=len(string1)
for i in range(0,length-1,2):
    print(string1[i])

"""Practice Question 7 : Print all Even numbers within the specified range

"""

start= int(input("Enter the start of the range"))
end = int(input("Enter the end of the range"))

for i in range(start,end):
  if(i%2==0):
    print(i)

"""Practice Question 8 : Removing first few characters from a string

"""

string1 = input("Enter a string")
num=int(input("Enter the number of characters to be removed"))

string2=string1[num:]
print(string2)

"""Practice Question 9 : Removing last few characters from a string

"""

string1 = input("Enter a string")
num=int(input("Enter the number of characters to be removed"))
length=len(string1)
num2= length-num
string2=string1[:num2]
print(string2)

"""Practice Question 10 : Counting a substring from a string"""

string1= input("enter your string")
string2 = input("enter the substring to be counted")

occurance = string1.count(string2)
print(occurance)

"""Practise Question 11 : Pattern 
      1
      22
      333
      4444
      55555
      
"""

